#!/usr/bin/python

import sys
import gtk
import appindicator
import os
import subprocess

class CamToggle:
    def __init__(self):
        self.ind = appindicator.Indicator("cam-toggle-indicator",
                                           "indicator-messages",
                                           appindicator.CATEGORY_APPLICATION_STATUS)
        self.ind.set_status(appindicator.STATUS_ACTIVE)
        self.ind.set_attention_icon("indicator-messages-new")
        self.ind.set_icon_theme_path("/usr/lib/camToggle")
        self.ind.set_icon('camon')

        # check if .camoff is present in home dir
        if(os.path.isfile("/usr/lib/camToggle/.camoff")):
            self.camOffCommand()

        # check status
        if (self.checkWebcamStatus()):
            self.ind.set_icon('camon')
        else:
            self.ind.set_icon('camoff')

        self.menuSetup()
        self.ind.set_menu(self.menu)

    def checkWebcamStatus(self):
        cmd = ['lsmod']
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        out, err = p.communicate()
        if "uvcvideo" in out:
            return True
        return False

    def menuSetup(self):
        self.menu = gtk.Menu()

        self.cam_on_item = gtk.MenuItem("Cam ON");
        self.cam_on_item.connect("activate", self.camOn)
        self.cam_on_item.show()

        self.cam_off_item = gtk.MenuItem("Cam OFF");
        self.cam_off_item.connect("activate", self.camOff)
        self.cam_off_item.show()

        self.quit_item = gtk.MenuItem("Quit")
        self.quit_item.connect("activate", self.quit)
        self.quit_item.show()

        self.menu.append(self.cam_on_item)
        self.menu.append(self.cam_off_item)
        self.menu.append(self.quit_item)

    def camOn(self, widget):
        self.camOnCommand()
        self.ind.set_icon('camon')

    def camOff(self, widget):
        self.camOffCommand()
        self.ind.set_icon('camoff')

    def camOnCommand(self):
        os.system("sudo /usr/lib/camToggle/camon")

    def camOffCommand(self):
        os.system("sudo /usr/lib/camToggle/camoff")

    def main(self):
        gtk.main()

    def quit(self, widget):
        sys.exit(0)

if __name__ == "__main__":
    indicator = CamToggle()
    indicator.main()
